# Generated by Django 4.0.6 on 2022-10-30 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_alter_job_description_alter_job_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='photo',
            field=models.ImageField(default=None, upload_to='pictures'),
            preserve_default=False,
        ),
    ]
